rsvplist.settings:
  type: config_object
  label:
  mapping:
  allowed_types:
    type: sequence
    label: Content types the RSVP Form can display on
    sequence: 
      type: string
      label: Content type